/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: ["bg-transparent"],
  theme: {
    fontWeight: {
      thin: '100',
      hairline: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    extend: {
      animation: {
        scan: 'scan 2s linear infinite',
        pulse: 'pulse 1.5s ease-in-out infinite',
      },
      keyframes: {
        scan: {
          '0%': { top: '0%' },
          '100%': { top: '100%' },
        },
        pulse: {
          '0%, 100%': { opacity: 0.3 },
          '50%': { opacity: 0.7 },
        },
      },
      backgroundImage: {
        'main': "url('/main.webp')",
      },
      fontFamily: {
        comfortaa: ['Comfortaa', 'sans-serif'],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        transparent: 'transparent',
        primary: '#1E90FF',
        main: '#007da0',
        secondary: '#6fd9e5',
        back: '#21A599',
        bgOrder: '#EFEFF4',
        bgInput: '#EBEBEE',
        historyBtn: '#EAB68F',
        slideBg: '#f0f0f0',
        quinary: '#8A2BE2',
        senary: '#00FF7F',
        septenary: '#FF69B4',
        octonary: '#FF4500',
        nonary: '#9370DB',
        closeCircle: '#20B2AA',
        darkAdmin: "#131922",
        light: 'F7F9FA',
        white: '#ffffff',
        black: '#000000',
        mainBg: '#bf6850',
        mainBgMiddle: '#ba7b6a',
        mainBgStart: '#ba9084',
        darkSwitch: '#2b2b2f',
        purple: '#3f3cbb',
        blue: '#316ff4',
        midnight: '#121063',
        metal: '#565584',
        tahiti: '#3ab7bf',
        silverAdmin: '#f0eef6',
        bubblegum: '#ff77e9',
        bermuda: '#78dcca',
        gray: '#808080',
        gray300: '#E0E0E0',
        gray500: '#9E9E9E',
        lightGray: '#D3D3D3',
        lightSlateGray: '#778899',
        darkGray: '#141616',
        veryDarkGray: '#272822',
        DimGray: '#696969',
        red: '#FF0000',
        orange: '#FFA500',
        orange600: '#FB8C00',
        dark: "#1d1d1d",
        silver: '#ecebff',
      },
    },
  },
  plugins: [],
};
