import type { Metadata } from "next";
import DisplacementSphere from './components/Background/DisplacementSphere';
import { ThemeProvider } from './components/Theme/ThemeProvider';
import "./globals.css";

export const metadata: Metadata = {
  title: "Techno Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/dist/tabler-icons.min.css" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <meta name="theme-color" content="#121212" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body className="relative w-full h-full overflow-x-hidden">
        <ThemeProvider>
          <div className="fixed top-0 left-0 w-full h-screen z-[-1]">
            <DisplacementSphere />
          </div>
          <div className="relative z-10 bg-transparent">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
